# SNAPSHOT build workflow
# 
# Bei jeder Änderung auf einem beliebigen branch wird ein SNAPSHOT maven build angestoßen,
# der die aktuelle Änderung compiliert und das resultierende SNAPSHOT Artefakt deployt,
# sofern in der pom.xml ein Plugin für das Deployment des Artefakts hiterlegt ist.
#
# Voraussetzungen:
# - Nutzung des artifactory-maven-plugin Plugins
# - Benutzer des Artifactories in den Secrets unter ARTIFACTORY_USERNAME hinterlegt
# - Token des Benutzers des Artifactories in den Secrets unter ARTIFACTORY_TOKEN hinterlegt
#
# Dieser Job wird bei jeder Änderung angestoßen.

name: Run snapshot build-job

on:
  push:
    branches: [ "**" ]

jobs:
  build-snapshot:

    name: SNAPSHOT build-job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
        run: mvn -B deploy --file pom.xml
